### ISSUE TITLE
Exporting (using Android Template) still always has com.giderosmobile.android as package

### ISSUE THREAD

**Issue by mydoghasworms** [gideros/gideros#155]
I am using version 2015.08 of Gideros.

When exporting, using the Android Template, I change the package, but in the export it still comes up as com.giderosmobile.android.

This issue had been reported previously in the forum and, it seems, resolved: http://giderosmobile.com/forum/discussion/4107/2013-9-1-android-export-bug-in-package-name/p1

**Comment by ar2rsawseen** [comment]
@mydoghasworms what do you mean by "still has com.giderosmobile.android" ? In Android manifest?

If you mean in packages (as in folders) then it is the way it should be, because all internal packages are linked to com.giderosmobile.android, but that does not change your app's package name (which should be the one you provided in export and should appear in Android Manifest)

**Comment by ar2rsawseen** [comment]
I can only assume this one was related to package name in the build.gradle and it was fixed here:
https://github.com/gideros/gideros/commit/5d316e57b341e48a9db895f6e4e51d09a49e50c8

if it is not, please reopen issue with more info
