### ISSUE TITLE
wrong (g)media plugin folder?

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#162]
the media plugin example project, when clicking on getpicture on windows gideros player, it gives the following error (appears after choosing a file):
call
.../AppData/Local/Temp/gideros/mediafiles/20150923_122146_gideros.png
media sizes	80	80
255	255	255	0
.../AppData/Local/Temp/gideros/Media/documents/20150923_122146_gideros.png: No such file or directory.
stack traceback:
	main.lua:63: in function <main.lua:25>

**Comment by N-1-c-k-e** [comment]
That's because the plugin writes images into "mediafiles" folder and this folder is not inside Gideros folder. You can access only "Resource", "Temp" and "Document" folders from Gideros core.
To workaround this bug you can use "Media:copy(filepath)" function to save this file into reachable place.

A workaround for media plugin example project:
media:copy("|T|test.png")
path = media:getPath()
...............................................................
bmp = Bitmap.new(Texture.new("|T|test.png", true))

**Comment by ar2rsawseen** [comment]
Interesting, what I do is actually store files in temp dir, using QDir::temp();

and that what it gives and provides a path, so yes as @N-1-c-k-e  said if you are going to use it, you can copy it to documents

This is done intentionally not to clutter documents folder too much :)
