### ISSUE TITLE
enhancement - gideros ide output window search, text highlighting

### ISSUE THREAD

**Issue by piretro** [gideros/gideros#186]
Now the search tool in the output window change the matching text color, but it's a pain for color blind people to find it in a long output text :)

Is it possible to highlight matching text background in a high contrast color combo (white text on red bg, or black text on yellow - for example), or just make the matching text "bold"?

Thank you

**Comment by ar2rsawseen** [comment]
At first I wanted to not to use colors but tried only bolding text more (because of the new studio themes, users can change colors to what they want and it may match the search color too) . But bold was not too obvious. So for now I've changed it to white text on red background. Should be contrast enough to see and not so popular combination to be used in themes :)

https://github.com/gideros/gideros/commit/02b3e1286c32014006a502e24848bcbfeb917c60
