### ISSUE TITLE
Built-in macro does not working same in desktop and mobile systems.

### ISSUE THREAD

**Issue by bugcaptor** [gideros/gideros#288]
In desktop player, you can declare built-in macro in a file (ex: init.lua) and use it in another file (ex: main.lua). But you cannot do this in android (and mobile platforms). Only macro in same file will be prepossessed properly.

Beside in desktop player, you cannot declare same macro among the source files. But you can do that in mobile platforms for the above reason.

I assume this is not intended. Fix needed.

**Comment by Nlcke** [comment]
The problem is `luac` runs new Lua state for each Lua source file so after macro expansion in one file (and converting a source to bytecode) Lua state is closed and global `MACRO` table which stores macro definitions is lost for next files.
Possible bugfix is to entirely remove current `luac` binary and run bytecode compiler written in Lua (http://lua-users.org/wiki/LuaCompilerInLua) via Gideros Players for desktops. It will respect file order and share same Lua state. This will also simplify Gideros building because currently we need to update and manually rebuild `luac` after each change in Lua library source code.

**Comment by SinisterSoft** [comment]
Or, we could possibly add all the files that are not excluded from execution into one file on export - then luac that file (and don't include the original files at all).  None execution files would run through luac as normal.

eg:

main.lua and mysprite.lua are set to executable.  controller.lua is set to none executable.

on export, a new file:  mysprite.lua is loaded, main.lua is then loaded, this new combined file gets exported though luac as main.lua.  controller.lua then also goes through luac as normal.


btw, do we currently strip debug info on export, if not then we should!

**Comment by SinisterSoft** [comment]
Fixed.
