### ISSUE TITLE
Test on more than one device (IP adress) simultaneously

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#31]
Assign more than one IP address in the Gideros IDE to test on multiple devices at the same time. Would be a great time saver when tuning differences in resolution and pixel density.

**Comment by SinisterSoft** [comment]
+1

**Comment by bali001** [comment]
+1

**Comment by ar2rsawseen** [comment]
My first step would be to implement broadcast in Gideros Studio which would send global ping and players would respond, so there would be a drop down list populated from responded devices, and IP address inserting would be an option, but not a necessity.

Because the main problem for running it on multiple devices is that device is the server and Studio is the client. So Studio would have to create multiple client connections and manage them.

Not impossible, but not so easy either :)

**Comment by totebo** [comment]
Sounds like a dream. Would speed up my workflow a lot.

**Comment by SinisterSoft** [comment]
Having an 'all' selection would be good - send to all at the same time. :)

**Comment by hgy29** [comment]
Now that we have surrounding players list, next step would be adding dev name (and timestamp would be good too) in front of each line outputed by players in the console

**Comment by SinisterSoft** [comment]
Only one player is active at once still isn't it ?

**Comment by totebo** [comment]
Yeah. The self discovery dropdown is a great improvement. The ability to send to all would be great. If it ran each IP in sequence (one after the other) that would work for me. I do that manually now.

**Comment by ar2rsawseen** [comment]
Can this be considered as done? :)

**Comment by hgy29** [comment]
Yes, it is done!
