### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#33]
With the new OpenGL 2 having to compile shaders at start and some people using LuaJIT, it might be a good idea for the system to display a splash screen as soon as possible. 

It would be good if the user could select it for the project, if nothing selected then it could display the 'Made with Gideros' splash screen?

**Comment by ar2rsawseen** [comment]
This is an interesting problem, because the Splash screen should start before the control was handed to the app.

So my first idea of making SplashScreen class available through lua will fail to help in this case.

So first step could be to optionally leave existing Gideros splash screen
Second step could be to replace the default Gideros icon with your own

**Comment by totebo** [comment]
I put my splash screens in init.lua. They appear pretty quickly. If the OpenGL 2 magic thing allows it to show even sooner, I'm all for it.

**Comment by hgy29** [comment]
In my tests, shaders compilation is really fast for most systems, notable exception being WinRT for custom shaders only (WinRT standard shaders are precompiled). I believe long 'blank screen' times are mainly due to lua interpreter/compiler.
If it is so, then it may be possible to add another export option to specify an asset to be used as a splash screen (texture), which gideros could show as splash screen.

**Comment by hgy29** [comment]
So we have splash screen now, right ? And with fake threads it becomes easy to initialise stuff in background.
