### ISSUE TITLE
Black area on screen

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#37]
On the latest version, Android, if you slide the system controls (the 3 android virtual buttons) in they are overlayed on the main game screen.  If you pick the 3rd one - to see the task list, then reselect the game then it has a black area on the screen where the buttons slid in.

**Comment by ar2rsawseen** [comment]
Unfortunately I don't have such device so can't experiment, but I'm almost certain this is due to the immersive view fix
https://github.com/gideros/gideros/commit/d65dc37d1d61a4557914c272e2c788b21500ca44

So there should be a way to capture such situation, maybe keycode, and refresh the surface somehow? :)

**Comment by SinisterSoft** [comment]
This will fix it:

getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE
	                    | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
	                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
	                    | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
	                    | View.SYSTEM_UI_FLAG_FULLSCREEN
	                    | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);

**Comment by ar2rsawseen** [comment]
Applied here:
https://github.com/gideros/gideros/commit/65dc35a11881ef1f376dae55eaf96da9c4c77d85
