### ISSUE TITLE
Some macro constant names conflict with Lua math.library

### ISSUE THREAD

**Issue by Apollo144** [gideros/gideros#390]
Hi! (I'm not sure if it's bug or not)

If we name a constant "max", it will spawn error, conflicting with math.max function:
```
max@100000
function keepInRange1()
	math.min(math.max(low, theVal), high)
end
```

If we make max regular variable, there's no errors:
```
max=100000
function keepInRange1()
	math.min(math.max(low, theVal), high)
end
```

**Comment by SinisterSoft** [comment]
That's because it's translated when compiled to bytecode as:
function keepInRange1()
   math.min(math.100000(low,theVal),high)
end

Macros are 'translated' before code is executed by the interpreter.  This allows them to have bytecode compile optimisations like pre processing expressions.

btw, you can do the same function with:
theVal=low><(high<>theVal)

see:  http://docs.giderosmobile.com/reference/enhancement/bigsmall

**Comment by Apollo144** [comment]
Got it, thanks!
