### ISSUE TITLE
TextField:setFont(font) does not work

### ISSUE THREAD

**Issue by MultiPain** [gideros/gideros#493]
Actually It works ONLY if you created an object with font.

```lua
local font1 = TTFont.new("GUI/Themes/green/font.ttf", 12)
local font2 = TTFont.new("GUI/Themes/random/font.ttf", 40)

local tf = TextField.new(font1, "Lorem ipsum dolor sit amet") --< OK (passed font1)
--local tf = TextField.new(nil, "Lorem ipsum dolor sit amet") --< NOT OK (passed nil, default font)
tf:setPosition(100,100)
tf:setScale(2)
stage:addChild(tf)

Timer.delayedCall(1000, function() 
	tf:setFont(font2)
end)
```

**Comment by hgy29** [comment]
This Is not a bug, but a restriction: you can’t change the kind of font used in a text field after it has been created. The default font is a bitmap font (Font object), so if you create a TextField with this font, you can’t change it later to a TTFont. 
This is because TextField code is heavily dependent on the font type used, so internally Gideros create of subclass of TextField specific to the font given during creation.
