### ISSUE TITLE
iOS export code and asset encryption not working

### ISSUE THREAD

**Issue by FuzzyDweeb** [gideros/gideros#70]
Tested v2015.04.26 today regards this and it does not work.

Only plain Lua code files work not encrypted ones on iOS export.

Crashes on first line of encrypted code in xCode.

**Comment by SinisterSoft** [comment]
More info on this:

He means that the files are encrypted ok, but the exported program crashes as soon as it hits an encrypted file.

**Comment by FuzzyDweeb** [comment]
That is correct :)

**Comment by hgy29** [comment]
Just did a test on my iPad / Xcode 6.3.1 and lua files encryption: everything works fine here. Did you do a full export (in an empty directory) ?

**Comment by FuzzyDweeb** [comment]
Er meh? Mine is broken on run if I encrypt it. Odd I will try again in morning to a fresh empty directory.

**Comment by SinisterSoft** [comment]
I spotted a bug in the current version of Gideros in that it won't overwrite certain files.  If you delete the export folder then export full again then it should fix it.

The bug about overwriting files will be fixed in the next version of Giders as it's already been commited by Arturs.  :)

https://github.com/gideros/gideros/commit/0b4d47b3d0ad010be2f3d82608887636fa8f2c8f

**Comment by FuzzyDweeb** [comment]
iOS: I tried again with export to a new empty dir like you said and it worked! - hooorah :D

**Comment by SinisterSoft** [comment]
:)

**Comment by ar2rsawseen** [comment]
Closing this issue then :)
