### ISSUE TITLE
XOR encryption key too short

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#71]
The xor encryption key is too short (unless it has been changed recently) as it's only a byte or two longer than some standard fixed headers (the lua bytecode header is one of them).   It would be better if set to something 256 bytes or longer.

**Comment by hgy29** [comment]
Agreed, 256 bytes sequence is a minimum for this kind of encryption, plus sequence shifts/modification along the encrypted file so that repetitions are harder to spot.
Also key location marker in generated file should be overwrited too to make it harder for an attacker to recover the key from the gideros lib itself

**Comment by hgy29** [comment]
Work in progress to address this :)

**Comment by hgy29** [comment]
Added encryption scheme enhancement in PR #75, as discussed with @SinisterSoft

**Comment by SinisterSoft** [comment]
:)

**Comment by ar2rsawseen** [comment]
PR Merged
