### ISSUE TITLE
MovieClip (scale) and hitTestPoint

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#81]
When changing scale with MovieClip, hitTestPoint didn't recognize the new scale.

Example:
sprite:setScale(0,0)
local mc = MovieClip.new{
	{1, 100, sprite, {scaleX = {0, 200, "linear"}}}
}

**Comment by ar2rsawseen** [comment]
There seems to be a specific problem with hitTestPoint after sprite was set to 0 scale
@hgy29 is working on it

**Comment by hgy29** [comment]
@tkhnoman, 
There is something weird in your example code: you set scaleX and scaleY to 0 as original sprite scale then ask for a linear widening only on scaleX (scaleY stay 0). Is it just a typo or not ?

**Comment by tkhnoman** [comment]
oh, typo. 
I just copy-pasted a code from example, since i have different handler.
Kind of forget how it works. Sorry for that.

**Comment by hgy29** [comment]
I meant, is there really a problem with hitTestPoint beside the typo or not ? Because I can't produce it!

My test case:
local sprite=Bitmap.new(Texture.new("texture.png"))
sprite:setScale(0)
stage:addChild(sprite)
local mc = MovieClip.new{
{1, 100, sprite, {scale = {0, 1, "linear"}}}
}
sprite:addEventListener(Event.MOUSE_DOWN,function ()
 print("click")
 end)

**Comment by tkhnoman** [comment]
I tested it again, it seems the bug only for scaleX and scaleY, this is the test code:

		local sprite=Bitmap.new(Texture.new("texture.png"))
		sprite:setScale(0)
		sprite:setPosition(100,100)
		stage:addChild(sprite)
		local mc = MovieClip.new{
		{1, 100, sprite, {scaleX = {0, 1, "linear"}}},
		{1, 100, sprite, {scaleY = {0, 1, "linear"}}},
		}
		sprite:addEventListener(Event.MOUSE_DOWN,function (event)
			if sprite:hitTestPoint(event.x,event.y) then
				print("click")
			end
		end)

**Comment by hgy29** [comment]
Ok, problem spotted.
sprite:setScale can accept 1,2 or 3 arguments for scaleX, scaleY and scaleZ factors, however if only one argument is given then it used for all three factors, and if only two are given, the third one (Z) is given the same value as the first (X). 
I think one arg behavior is correct, however this breaks compatibility a bit since if scaleZ is set to 0 it will cause hitTestPoint to fail, so user must be aware of that. I can make it so that one arg call leave Z as-is too, this will keep compat but may seem strange if we think that one arg call is 'scale in all axis)
Two args behavior is incorrect: if x and Y where given, then z should be left unchanged.

So @tkhnoman, it will work if you use sprite:setScale(0,0,1), and should have worked with sprite:setScale(0,0).

About the one arg case, what do you think ? ScaleZ too or leave it untouched ?

**Comment by tkhnoman** [comment]
I myself, actually never use one arg, and always using three arg when handling with 3d objects.
But probably would be better to change scaleZ too.

I wonder why hitTestPoint fail on scaleZ == 0 (since it's actually just flat, not gone)?

**Comment by hgy29** [comment]
> I wonder why hitTestPoint fail on scaleZ == 0 (since it's actually 
> just flat, not gone)?

Because as of today hitTestPoint works by transforming screen 
coordinates back to sprite local coordinates, while drawing works the 
opposite way, i.e sprite coordinates are transformed to screen coordinates.
If you scale something, you multiply coordinates by the scale factor, if 
you want to reverse the process, then you have to divide by the scale 
factor. The thing is while multiplying by 0 is easy, dividing by 0 is 
mathematically impossible...

In fact I'd like to make hitTestPoint work the forward way (Sprite -> 
Screen) and check hit in screen coordinates, this would also solve the 
issue of hitTest along Z axis (because perspective transform is not 
reversible either). But again the path to this is unclear and 
error/incompat prone...

**Comment by john-blackburn** [comment]
It might be best for now to just guard against scale=0 and treat it as a special case thus avoiding divide by zero

John

-----Original Message-----

**Comment by ar2rsawseen** [comment]
It should be fixed in https://github.com/gideros/gideros/commit/3224703d2a1d578076ab9fe5d4bdd1bb49a16345
